[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

anyhow.workspace = true
cfg-if.workspace = true
chrono.workspace = true
http.workspace = true
serde.workspace = true
thiserror.workspace = true

axum = { workspace = true, optional = true }
log = { workspace = true, optional = true }
pulldown-cmark = { workspace = true, optional = true }
serde_yml = { workspace = true, optional = true }
slug = { workspace = true, optional = true }


[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:axum",
    "dep:leptos_axum",
    "dep:log",
    "dep:pulldown-cmark",
    "dep:serde_yml",
    "dep:slug",
]
